FROM maven:3.8.5-openjdk-17 AS builder
WORKDIR groceryexpress
COPY ./GroceryExpress ./
RUN mvn clean install

FROM openjdk:17 AS backend
WORKDIR groceryexpress
COPY --from=builder /groceryexpress/target/GroceryExpress-0.0.1-SNAPSHOT.jar /groceryexpress/GroceryExpress-0.0.1-SNAPSHOT.jar
EXPOSE 8080
CMD ["java", "-jar", "/groceryexpress/GroceryExpress-0.0.1-SNAPSHOT.jar"]

